import { useEffect, useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import type { Column, Notify } from '../types';
import type { RetributionFilter } from '../components/Shared';
import { DataTable, ExportButton, PageHeader, RetributionFilterPanel, Tabs } from '../components/Shared';
import { exportRetributionRecap, exportRetributionReport } from '../api/retribution';
import { getApiErrorMessage, getExportFilename } from '../api/simpada';
import { useRetributionRecap, useRetributionReport, useRetributionSources } from '../hooks/useRetributionReport';
import { adaptRetributionPagination, adaptRetributionRecapRows, adaptRetributionRows, type RetributionRecapParams, type RetributionRecapSortField, type RetributionReportParams, type RetributionSortField } from '../types/retribution';
import type { SimpadaSortDirection } from '../types/simpada';

const monitoringOrder: RetributionSortField[] = ['document_number','taxpayer_number','opd_name','retribution_type_name','tax_period','transaction_date','assessment_amount','payment_status'];
const monitoringDefinitions: Record<RetributionSortField, Column> = {
  transaction_date:{key:'transaction_date',label:'Tanggal Input',width:'12%'}, taxpayer_number:{key:'taxpayer_number',label:'No NPWRD',width:'13%'}, document_number:{key:'document_number',label:'No SKRD',width:'14%'}, opd_id:{key:'opd_id',label:'ID OPD'}, opd_name:{key:'opd_name',label:'Nama OPD',width:'19%'},  tax_period:{key:'tax_period',label:'Masa Retribusi',width:'12%'}, assessment_amount:{key:'assessment_amount',label:'Jumlah Retribusi',money:true,width:'13%'}, payment_amount:{key:'payment_amount',label:'Jumlah Bayar',money:true}, payment_date:{key:'payment_date',label:'Tanggal Bayar'}, payment_status:{key:'payment_status',label:'Status Bayar',width:'13%'}, status_code:{key:'status_code',label:'Kode Status'}, retribution_type_id:{key:'retribution_type_id',label:'ID Jenis Retribusi'}, retribution_type_name:{key:'retribution_type_name',label:'Jenis Retribusi',width:'17%'},
};
const recapOrder: RetributionRecapSortField[] = ['opd_id','opd_name','january','february','march','april','may','june','july','august','september','october','november','december','annual_total'];
const monthLabels: Record<string,string> = { january:'Jan',february:'Feb',march:'Mar',april:'Apr',may:'Mei',june:'Jun',july:'Jul',august:'Agu',september:'Sep',october:'Okt',november:'Nov',december:'Des' };
const recapDefinitions = Object.fromEntries(recapOrder.map(field => [field,{key:field,label:field==='opd_id'?'ID OPD':field==='opd_name'?'Nama OPD':field==='annual_total'?'Total':monthLabels[field],...(!['opd_id','opd_name'].includes(field)?{money:true}:{})}])) as Record<RetributionRecapSortField,Column>;
export function buildRetributionColumns(fields: string[] = []) { const available=new Set(fields); return monitoringOrder.filter(field=>!fields.length||available.has(field)).map(field=>monitoringDefinitions[field]); }
export function buildRetributionRecapColumns(fields: string[] = []) { const available=new Set(fields); return recapOrder.filter(field=>!fields.length||available.has(field)).map(field=>recapDefinitions[field]); }

export function RetributionReportPage({ notify }: { notify: Notify }) {
  const location=useLocation(); const activeTab=new URLSearchParams(location.search).get('tab')==='Rekap OPD'?'Rekap OPD':'Monitoring'; const isRecap=activeTab==='Rekap OPD';
  const currentYear=new Date().getFullYear(); const [filter,setFilter]=useState<RetributionFilter>({year:currentYear}); const [search,setSearch]=useState(''); const [debouncedSearch,setDebouncedSearch]=useState(''); const [sort,setSort]=useState<{key:string;direction:SimpadaSortDirection}|null>(null); const [page,setPage]=useState(1); const [perPage,setPerPage]=useState(10); const [exporting,setExporting]=useState(false); const [errorText,setErrorText]=useState<string>();
  useEffect(()=>{const timer=window.setTimeout(()=>{setDebouncedSearch(search.slice(0,200));setPage(1)},400);return()=>window.clearTimeout(timer)},[search]);
  useEffect(()=>{setPage(1);setSort(null)},[activeTab,filter]);
  const reportParams=useMemo<RetributionReportParams>(()=>({year:filter.year,...(filter.month?{month:filter.month}:{}),...(filter.source?{source:filter.source}:{}),...(debouncedSearch?{search:debouncedSearch}:{}),...(sort&&monitoringOrder.includes(sort.key as RetributionSortField)?{sort_by:sort.key as RetributionSortField,sort_direction:sort.direction}:{}),page,per_page:perPage}),[filter,debouncedSearch,sort,page,perPage]);
  const recapParams=useMemo<RetributionRecapParams>(()=>({year:filter.year,...(debouncedSearch?{search:debouncedSearch}:{}),...(sort&&recapOrder.includes(sort.key as RetributionRecapSortField)?{sort_by:sort.key as RetributionRecapSortField,sort_direction:sort.direction}:{}),page,per_page:perPage}),[filter.year,debouncedSearch,sort,page,perPage]);
  const sourcesQuery=useRetributionSources(); const reportQuery=useRetributionReport(reportParams,!isRecap); const recapQuery=useRetributionRecap(recapParams,isRecap); const activeQuery=isRecap?recapQuery:reportQuery;
  useEffect(()=>{if(activeQuery.error)getApiErrorMessage(activeQuery.error).then(setErrorText);else setErrorText(undefined)},[activeQuery.error]);
  const pagination=adaptRetributionPagination(activeQuery.data,page,perPage); const columns=isRecap?buildRetributionRecapColumns(recapQuery.data?.meta.columns):buildRetributionColumns(reportQuery.data?.meta.columns); const rows=isRecap?adaptRetributionRecapRows(recapQuery.data?.data||[]):adaptRetributionRows(reportQuery.data?.data||[]);
  const download=async()=>{setExporting(true);try{const response=isRecap?await exportRetributionRecap(recapParams):await exportRetributionReport(reportParams);const url=URL.createObjectURL(response.data);const link=document.createElement('a');link.href=url;link.download=getExportFilename(response.headers['content-disposition'] as string|undefined,isRecap?`rekap-ketetapan-retribusi-per-opd-${filter.year}.xlsx`:`laporan-retribusi-global-${filter.year}.xlsx`);document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(error){notify(`Ekspor gagal: ${await getApiErrorMessage(error)}`)}finally{setExporting(false)}};
  const server={query:search,sort:sort?.key||null,direction:sort?.direction||null,page:pagination.page,size:pagination.perPage,total:pagination.total,rowCount:pagination.rowCount,pages:pagination.pages,sortableKeys:columns.map(column=>column.key),loading:activeQuery.isFetching,error:errorText,onQueryChange:setSearch,onSortChange:(key:string,direction:SimpadaSortDirection)=>{setSort({key,direction});setPage(1)},onPageChange:setPage,onSizeChange:(size:number)=>{setPerPage(size);setPage(1)}};
  return <><PageHeader title={`Data ${activeTab} Retribusi Daerah`} description="Monitoring target dan realisasi retribusi berdasarkan OPD pengelola." action={<ExportButton notify={notify} onClick={download} disabled={exporting} loading={exporting}/>}/><Tabs items={['Monitoring','Rekap OPD']}/><RetributionFilterPanel value={filter} sources={sourcesQuery.data?.data||[]} yearOnly={isRecap} onApply={next=>{setFilter(isRecap?{year:next.year}:next);setPage(1)}}/><DataTable columns={columns} rows={rows} wide={isRecap} pageSizeOptions={[10,25,50,100]} server={server}/></>;
}
