import { describe,expect,it } from 'vitest';
import { buildRetributionColumns,buildRetributionRecapColumns } from '../pages/RetributionReportPage';
import { adaptRetributionPagination,adaptRetributionRecapRows,adaptRetributionRows,type RetributionReportResponse } from './retribution';

describe('adapter laporan Retribusi',()=>{
  it('memakai pagination API tanpa slicing client',()=>{const response={meta:{total:31,row_count:1,columns:[],pagination:{current_page:3,per_page:10,last_page:4}},data:[]} as RetributionReportResponse;expect(adaptRetributionPagination(response,1,25)).toEqual({page:3,perPage:10,pages:4,total:31,rowCount:1})});
  it('mempertahankan identifier nol awal, nominal, dan status response tanpa menghitung ulang',()=>{const raw={transaction_date:'2026-09-05',taxpayer_number:'000123',document_number:'0007/SKRD',opd_id:'04',opd_name:'Dinas Contoh',tax_period:'09-2026',assessment_amount:'100.50',payment_amount:'0',payment_date:null,payment_status:'Status Backend Khusus',status_code:'paid',payment_match_status:'found',retribution_type_id:'015',retribution_type_name:'Pariwisata'};const [row]=adaptRetributionRows([raw]);expect(row).toMatchObject({transaction_date:'05-09-2026',taxpayer_number:'000123',document_number:'0007/SKRD',assessment_amount:'100.50',payment_amount:'0',payment_date:'-',payment_status:'Status Backend Khusus',retribution_type_id:'015'});expect(row).not.toHaveProperty('number');expect(row).not.toHaveProperty('source_record_id');expect(row).not.toHaveProperty('payment_match_status');expect(raw.transaction_date).toBe('2026-09-05')});
  it('mengikuti meta columns sambil menyembunyikan field internal',()=>{expect(buildRetributionColumns(['number','source_record_id','transaction_date','payment_status','payment_match_status']).map(c=>c.key)).toEqual(['transaction_date','payment_status'])});
  it('rekap tidak menampilkan number dan mempertahankan string desimal serta nol awal ID',()=>{const columns=buildRetributionRecapColumns(['number','opd_id','opd_name','january','annual_total']);expect(columns.map(c=>c.key)).toEqual(['opd_id','opd_name','january','annual_total']);expect(columns[2].money).toBe(true);expect(adaptRetributionRecapRows([{number:1,opd_id:'004',opd_name:'Dinas',january:'100.25',february:'0',march:'0',april:'0',may:'0',june:'0',july:'0',august:'0',september:'0',october:'0',november:'0',december:'0',annual_total:'100.25'}])[0]).toMatchObject({opd_id:'004',january:'100.25',annual_total:'100.25'})});
});
