import{Link,Navigate,useParams}from'react-router-dom';import{AppHeader}from'../components/AppHeader';import{ErrorState,Loading}from'../components/States';import{usePbbHistory}from'../hooks/usePbb';import{formatNop,isValidNop,rupiah}from'../utils/format';

const labels=['Tahun Pajak','Nama Wajib Pajak','Tanggal Jatuh Tempo','Jlh Denda Bulan & Persen','Jumlah Tagihan','Denda','Jumlah Tagihan + Denda','Dibayar','Tanggal Dibayar','Status','Action'];
const icons=[
<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></svg>,
<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></svg>,
<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/></svg>,
<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 7V5a2 2 0 0 1 2-2h12v4"/><rect x="3" y="7" width="18" height="14" rx="2"/><path d="M16 13h5v4h-5a2 2 0 0 1 0-4Z"/></svg>
];
export default function HistoryPage(){const{nop=''}=useParams(),q=usePbbHistory(nop);if(!isValidNop(nop))return <Navigate to="/" replace/>;const records=q.data??[],paid=records.filter(r=>r.status==='Lunas').length,unpaid=records.length-paid,active=records.filter(r=>r.status==='Belum').reduce((sum,r)=>sum+r.total,0);const stats=[['Total Tahun Pajak',String(records.length)],['Total Lunas',String(paid)],['Total Belum Bayar',String(unpaid)],['Total Tagihan Aktif',rupiah(active)]];return <div className="history-page"><AppHeader backTo="/" backLabel="Kembali ke Beranda"/><main><section className="container intro" aria-labelledby="page-title"><span className="eyebrow">Riwayat pembayaran PBB</span><h1 id="page-title">Histori PBB</h1><p className="lead">Daftar riwayat SPPT Pajak Bumi dan Bangunan untuk NOP <strong>{formatNop(nop)}</strong>.</p></section>{q.isLoading?<Loading/>:q.isError?<ErrorState retry={()=>q.refetch()}/>:<section className="container" aria-label="Informasi histori PBB"><div className="stats-grid" aria-label="Statistik histori PBB">{stats.map((stat,i)=><div className="stat-card history-reveal" style={{animationDelay:`${i*40}ms`}} key={stat[0]}><div className="stat-copy"><span className="stat-label">{stat[0]}</span><strong className="stat-value">{stat[1]}</strong></div><span className="stat-icon" aria-hidden="true">{icons[i]}</span></div>)}</div><article className="card history-reveal history-table-card"><div className="card-head"><div><h2>Riwayat SPPT</h2><p>Catatan tagihan dan pembayaran tahun pajak 2015–2026.</p></div></div><div className="table-wrap"><table><thead><tr>{labels.map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{records.map(r=><tr key={r.year} className={r.status==='Belum'?'unpaid-row':''}><td data-label={labels[0]}>{r.year}</td><td data-label={labels[1]}>{r.taxpayerName}</td><td data-label={labels[2]}>{r.dueDate}</td><td data-label={labels[3]}>{r.penaltyInfo}</td><td data-label={labels[4]} className="amount money">{rupiah(r.principal)}</td><td data-label={labels[5]} className="money">{rupiah(r.penalty)}</td><td data-label={labels[6]} className="amount money">{rupiah(r.total)}</td><td data-label={labels[7]} className="amount money">{rupiah(r.paid)}</td><td data-label={labels[8]}>{r.paidDate}</td><td data-label={labels[9]}><span className={`badge ${r.status==='Belum'?'unpaid':''}`}>{r.status}</span></td><td data-label={labels[10]}><Link className={`detail-btn ${r.status==='Belum'?'pay-now':''}`} to={`/pbb/${nop}/${r.year}`}>{r.status==='Belum'?'Bayar Sekarang':'Lihat Detail'}</Link></td></tr>)}</tbody></table></div></article></section>}</main></div>}
