import {useRef,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {formatNop,nopDigits} from '../utils/format'
import logo from '../../logo.png'
import faqImage from '../assets/faq.jpeg'
import bankSumut from '../../channels/banksumut.png'
import bri from '../../channels/bri.svg'
import btn from '../../channels/btn.png'
import pos from '../../channels/pos.png'
import indomaret from '../../channels/indomaret.png'
import alfamart from '../../channels/alfamart.png'
import dana from '../../channels/dana.svg'
import gopay from '../../channels/gopay.svg'
import qris from '../../channels/qris.svg'

const paymentChannels=[
  {name:'Bank Sumut',logo:bankSumut},{name:'BRI',logo:bri},{name:'BTN',logo:btn},
  {name:'Kantor Pos',logo:pos},{name:'Indomaret',logo:indomaret},{name:'Alfamart',logo:alfamart},
  {name:'DANA',logo:dana},{name:'GoPay',logo:gopay},{name:'QRIS',logo:qris}
]
const Svg=({children}:{children:React.ReactNode})=><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true">{children}</svg>
const pbbServices=[
  {icon:<Svg><path d="M5 3h10l4 4v14H5V3Z"/><path d="M15 3v5h4M8 12h5M8 16h3"/><circle cx="16.5" cy="16.5" r="2.5"/><path d="m18.3 18.3 2 2"/></Svg>,title:'Cek Tagihan',copy:'Lihat nominal dan rincian PBB berdasarkan NOP.'},
  {icon:<Svg><circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2M7 4 4 7H4"/></Svg>,title:'Lihat Histori',copy:'Pantau pembayaran PBB dari tahun ke tahun dalam satu halaman.'},
  {icon:<Svg><rect x="3" y="5" width="18" height="14" rx="3"/><path d="M3 10h18M7 15h4"/><path d="m15 15 1.5 1.5L20 13"/></Svg>,title:'Bayar Aman',copy:'Lanjutkan pembayaran melalui kanal digital resmi.'}
]
const otherServices=[
  {icon:pbbServices[0].icon,title:'Cek Ketetapan',copy:'Lihat rincian ketetapan pajak daerah berdasarkan NOPD.'},
  {icon:pbbServices[1].icon,title:'Lihat Status',copy:'Pantau status dan informasi pembayaran pajak daerah Anda.'},
  {icon:pbbServices[2].icon,title:'Bayar Aman',copy:'Gunakan kanal pembayaran pajak daerah yang resmi dan terpercaya.'}
]
export default function HomePage(){
  const [tab,setTab]=useState<'pbb'|'other'>('pbb'),[value,setValue]=useState(''),[nopd,setNopd]=useState(''),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null),nav=useNavigate()
  const reset=()=>setError('')
  const changeTab=(next:'pbb'|'other')=>{setTab(next);reset();requestAnimationFrame(()=>input.current?.focus())}
  const submit=()=>{if(tab==='other'){if(!nopd.trim()){setError('NOPD belum diisi.');input.current?.focus();return}setError('Pencarian pajak daerah lainnya sedang dalam pengembangan.');return}const digits=nopDigits(value);if(digits.length!==18){setError(`NOP belum lengkap. Masukkan tepat 18 digit (${digits.length}/18 digit).`);input.current?.focus();return}reset();nav(`/pbb/${digits}/history`)}
  const currentValue=tab==='pbb'?value:nopd
  const isPbb=tab==='pbb',activeServices=isPbb?pbbServices:otherServices
  return <div className="prototype-home"><header className="home-hero" id="beranda"><div className="home-hero-inner"><div className="home-agency"><span className="home-agency-logo"><img src={logo} alt="Logo Kabupaten Batu Bara"/></span><span className="home-agency-copy"><small>Pemerintah Kabupaten Batu Bara</small><strong>Badan Pendapatan Daerah</strong></span></div><h1>Sistem Informasi Cek Pajak Online</h1><p>Periksa histori pajak, rincian perhitungan, status pembayaran, dan lakukan pembayaran digital dalam satu portal layanan yang transparan dan aman.</p><div className="search-field"><div className={`tax-search-tabs ${tab==='other'?'show-other':''}`} role="tablist" aria-label="Jenis pajak"><span className="tax-tab-slider" aria-hidden="true"/><button type="button" role="tab" aria-selected={tab==='pbb'} className={tab==='pbb'?'active':''} onClick={()=>changeTab('pbb')}>PBB</button><button type="button" role="tab" aria-selected={tab==='other'} className={tab==='other'?'active':''} onClick={()=>changeTab('other')}>Pajak Daerah Lainnya</button></div><div className="prototype-search"><div className="input-wrap"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input ref={input} type="search" inputMode={tab==='pbb'?'numeric':'text'} maxLength={tab==='pbb'?24:40} value={currentValue} onChange={e=>{tab==='pbb'?setValue(formatNop(e.target.value)):setNopd(e.target.value.toUpperCase());reset()}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();submit()}}} placeholder={tab==='pbb'?'Contoh: 12.21.140.015.010.0373-0':'Masukkan NOPD'} autoComplete="off" aria-describedby="search-help" aria-invalid={error?true:undefined} className={error?'input-error':''}/><button className={`clear ${currentValue?'show':''}`} type="button" aria-label="Hapus pencarian" onClick={()=>{tab==='pbb'?setValue(''):setNopd('');reset();input.current?.focus()}}>×</button></div><button className="search-btn" type="button" onClick={submit}>Cari Data Pajak</button></div><div className={`prototype-search-help ${error?'error':''}`} id="search-help">{error||(tab==='pbb'?'Masukkan 18 digit NOP yang tertera pada SPPT PBB.':'Masukkan NOPD pajak daerah Anda.')}</div></div></div></header><main className="prototype-main">
  <section className="landing-overview" id="informasi"><div className="container landing-overview-grid"><div className="landing-intro home-reveal"><h2>Cek Pajak Lebih Mudah dalam Satu Portal</h2><p>{isPbb?'Masukkan 18 digit NOP yang tercantum pada SPPT PBB untuk melihat informasi objek pajak, status tagihan, histori pembayaran, dan pilihan pembayaran.':'Masukkan NOPD yang tercantum pada SKPD untuk melihat informasi ketetapan, status, dan pilihan pembayaran pajak daerah lainnya.'}</p></div><div className="service-list">{activeServices.map((x,i)=><article className="service-row home-reveal" style={{animationDelay:`${i*80}ms`}} key={`${tab}-${x.title}`}><span className="prototype-icon">{x.icon}</span><div><h3>{x.title}</h3><p>{x.copy}</p></div></article>)}</div><div className="tax-info-bar" id="panduan"><span className="tax-info-icon" aria-hidden="true">i</span><p>{isPbb?'Pastikan seluruh 18 digit NOP sudah benar, simpan bukti transaksi, dan gunakan hanya kanal pembayaran resmi.':'Pastikan NOPD sesuai dengan SKPD, periksa data ketetapan yang tampil, dan gunakan hanya kanal pembayaran resmi.'}</p></div></div></section>
  <section className="landing-help"><div className="container faq-compact"><div className="faq-visual"><img src={faqImage} alt="Layanan informasi pajak SICEPOL"/></div><div className="faq-content"><div className="faq-compact-head"><h2>Pertanyaan Seputar SICEPOL</h2><p>{isPbb?'Temukan jawaban seputar NOP, tagihan, histori, dan pembayaran PBB melalui SICEPOL.':'Temukan informasi seputar NOPD, ketetapan, status, dan pembayaran pajak daerah lainnya.'}</p></div><div className="faq-list" key={tab} onClick={event=>{const summary=(event.target as HTMLElement).closest('summary');if(!summary)return;const selected=summary.parentElement;summary.closest('.faq-list')?.querySelectorAll('details[open]').forEach(item=>{if(item!==selected)item.removeAttribute('open')})}}>{isPbb?<><details open><summary>Di mana saya dapat menemukan NOP?</summary><p>NOP terdiri dari 18 digit dan dapat ditemukan pada SPPT PBB. Masukkan angka tersebut ke kolom pencarian sesuai urutannya.</p></details><details><summary>Mengapa data pajak tidak ditemukan?</summary><p>Pastikan seluruh 18 digit NOP telah dimasukkan dengan benar. Jika data tetap tidak ditemukan, hubungi Bapenda melalui kanal resmi.</p></details><details><summary>Mengapa pembayaran saya belum tercatat?</summary><p>Pembaruan status dapat memerlukan waktu pemrosesan. Simpan bukti pembayaran dan lakukan pengecekan kembali secara berkala.</p></details><details><summary>Apakah pengecekan data PBB dikenakan biaya?</summary><p>Tidak. Pengecekan tagihan, status, dan histori pembayaran melalui SICEPOL dapat dilakukan tanpa biaya layanan.</p></details><details><summary>Apakah SICEPOL dapat digunakan melalui ponsel?</summary><p>Ya. SICEPOL dapat diakses melalui peramban pada ponsel, tablet, maupun komputer yang terhubung ke internet.</p></details></>:<><details open><summary>Di mana saya dapat menemukan NOPD?</summary><p>NOPD tercantum pada SKPD pajak daerah Anda.</p></details><details><summary>Pajak apa saja yang dapat diperiksa?</summary><p>Layanan ini ditujukan untuk jenis pajak daerah selain PBB yang telah terdaftar pada sistem Bapenda.</p></details><details><summary>Mengapa data NOPD tidak ditemukan?</summary><p>Periksa kembali penulisan NOPD. Jika data tetap tidak ditemukan, hubungi Bapenda melalui kanal resmi.</p></details><details><summary>Apakah pengecekan pajak daerah dikenakan biaya?</summary><p>Tidak. Pengecekan informasi pajak daerah melalui SICEPOL tidak dikenakan biaya layanan.</p></details><details><summary>Bagaimana jika pembayaran belum tercatat?</summary><p>Simpan bukti pembayaran dan periksa kembali status pembayaran secara berkala.</p></details></>}</div></div></div></section>
  <section className="other-services" aria-labelledby="other-services-title"><div className="container"><div className="other-services-head"><h2 id="other-services-title">Layanan Bapenda Lainnya</h2><p>Akses berbagai layanan pajak daerah dan administrasi Bapenda Kabupaten Batu Bara melalui kanal resmi yang tersedia.</p></div><div className="other-services-grid"><a className="other-service-card service-website" href="https://bapenda.batubarakab.go.id/" target="_blank" rel="noopener noreferrer"><span className="other-service-icon"><Svg><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/></Svg></span><span className="other-service-copy"><strong>Website Resmi Bapenda</strong><small>Informasi, berita, dan layanan resmi Bapenda Kabupaten Batu Bara.</small></span><span className="other-service-link">Kunjungi <span aria-hidden="true">→</span></span></a><a className="other-service-card service-realisasi" href="https://realisasibapenda.batubarakab.go.id/" target="_blank" rel="noopener noreferrer"><span className="other-service-icon"><Svg><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/><path d="m4 7 5-4 5 4 6-5"/></Svg></span><span className="other-service-copy"><strong>Realisasi PAD</strong><small>Pantau capaian dan perkembangan realisasi Pendapatan Asli Daerah.</small></span><span className="other-service-link">Kunjungi <span aria-hidden="true">→</span></span></a><a className="other-service-card service-pbb" href="https://e-pbb.batubarakab.go.id/" target="_blank" rel="noopener noreferrer"><span className="other-service-icon"><Svg><path d="M4 21V8l8-5 8 5v13M2 21h20M9 21v-6h6v6"/><path d="M8 10h2M14 10h2"/></Svg></span><span className="other-service-copy"><strong>E-PBB</strong><small>Akses layanan administrasi Pajak Bumi dan Bangunan secara digital.</small></span><span className="other-service-link">Kunjungi <span aria-hidden="true">→</span></span></a><a className="other-service-card service-bphtb" href="https://e-bphtb.batubarakab.go.id/" target="_blank" rel="noopener noreferrer"><span className="other-service-icon"><Svg><path d="M3 11 12 4l9 7M5 10v10h14V10M9 20v-6h6v6"/><path d="m16 6 2-2 2 2"/></Svg></span><span className="other-service-copy"><strong>E-BPHTB</strong><small>Kelola layanan Bea Perolehan Hak atas Tanah dan Bangunan secara online.</small></span><span className="other-service-link">Kunjungi <span aria-hidden="true">→</span></span></a></div></div></section>
  <section className="payment-partners" aria-labelledby="payment-partners-title"><div className="container payment-partners-head"><h2 id="payment-partners-title">Mitra Pembayaran Pajak Daerah</h2><span className="payment-partners-line" aria-hidden="true"/><p>Bayar pajak daerah Anda dengan mudah melalui berbagai channel pembayaran resmi yang tersedia.</p></div><div className="payment-marquee"><span className="payment-marquee-fade payment-marquee-fade-left"/><span className="payment-marquee-fade payment-marquee-fade-right"/><div className="marquee-track">{[...paymentChannels,...paymentChannels].map((channel,index)=><div className="payment-channel-card" key={`${channel.name}-${index}`}><img src={channel.logo} alt={channel.name}/><p>{channel.name}</p></div>)}</div></div></section>
</main></div>}
