import {useRef,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {AppFooter} from '../components/AppFooter'
import {formatNop,nopDigits} from '../utils/format'

const Svg=({children}:{children:React.ReactNode})=><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true">{children}</svg>
const steps=[
  {icon:<Svg><circle cx="10" cy="10" r="6"/><path d="m14.5 14.5 5 5"/></Svg>,title:'Masukkan NOP',copy:'Ketik 18 digit Nomor Objek Pajak sesuai yang tercantum pada SPPT PBB Anda.'},
  {icon:<Svg><path d="M6 3h12v18H6V3Z"/><path d="M9 8h6m-6 4h6m-6 4h3"/></Svg>,title:'Periksa Data Pajak',copy:'Tinjau rincian tagihan, riwayat, dan status pembayaran yang tersedia untuk objek pajak.'},
  {icon:<Svg><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="3"/></Svg>,title:'Bayar Digital',copy:'Lanjutkan pembayaran melalui pilihan kanal digital yang tersedia pada layanan.'}
]
const information=[
  {icon:<Svg><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6m-6 4h6"/></Svg>,title:'Rincian Tagihan PBB',copy:'Lihat informasi tagihan Pajak Bumi dan Bangunan berdasarkan NOP.'},
  {icon:<Svg><path d="M20 7v5h-5M4 17v-5h5M6 8a7 7 0 0 1 12-2l2 2M4 16l2 2a7 7 0 0 0 12-2"/></Svg>,title:'Riwayat Pembayaran',copy:'Telusuri catatan pembayaran pajak yang telah tersedia dalam sistem.'},
  {icon:<Svg><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></Svg>,title:'Status Pembayaran',copy:'Periksa status pelunasan agar informasi kewajiban pajak tetap terpantau.'},
  {icon:<Svg><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M7 9H5m14 6h-2"/><circle cx="12" cy="12" r="3"/></Svg>,title:'Pembayaran Digital',copy:'Akses kanal pembayaran digital yang disediakan melalui alur layanan resmi.'}
]
export default function HomePage(){
  const [value,setValue]=useState(''),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null),nav=useNavigate()
  const reset=()=>setError('')
  const submit=()=>{const digits=nopDigits(value);if(digits.length!==18){setError(`NOP belum lengkap. Masukkan tepat 18 digit (${digits.length}/18 digit).`);input.current?.focus();return}reset();nav(`/pbb/${digits}/history`)}
  return <div className="prototype-home"><header className="home-hero" id="beranda"><div className="home-hero-inner"><div className="home-agency"><span className="home-agency-logo"><img src="/logo.png" alt="Logo Kabupaten Batu Bara"/></span><span className="home-agency-copy"><small>Pemerintah Kabupaten Batu Bara</small><strong>Badan Pendapatan Daerah</strong></span></div><h1>Sistem Informasi Cek Pajak Online</h1><p>Periksa histori pajak, rincian perhitungan, status pembayaran, dan lakukan pembayaran digital dalam satu portal layanan yang transparan dan aman.</p><div className="search-field"><div className="prototype-search"><div className="input-wrap"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input ref={input} type="search" inputMode="numeric" maxLength={24} value={value} onChange={e=>{setValue(formatNop(e.target.value));reset()}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();submit()}}} placeholder="Contoh: 12.21.140.015.010.0373-0" autoComplete="off" aria-describedby="search-help" aria-invalid={error?true:undefined} className={error?'input-error':''}/><button className={`clear ${value?'show':''}`} type="button" aria-label="Hapus pencarian" onClick={()=>{setValue('');reset();input.current?.focus()}}>×</button></div><button className="search-btn" type="button" onClick={submit}>Cari Data Pajak</button></div><div className={`prototype-search-help ${error?'error':''}`} id="search-help">{error||'Masukkan 18 digit NOP yang tertera pada SPPT PBB.'}</div></div></div></header><main className="prototype-main">
  <section className="prototype-section" id="cara"><div className="container"><SectionHead kicker="Mudah dan praktis" title="Cara Menggunakan SICEPOL" copy="Akses informasi pajak Anda dalam tiga langkah sederhana melalui layanan SICEPOL."/><div className="prototype-grid steps">{steps.map((x,i)=><article className="step home-reveal" style={{animationDelay:`${i*100}ms`}} key={x.title}><span className="step-number">0{i+1}</span><span className="prototype-icon">{x.icon}</span><h3>{x.title}</h3><p>{x.copy}</p></article>)}</div></div></section>
  <section className="prototype-section info-section" id="informasi"><div className="container"><SectionHead kicker="Informasi layanan" title="Informasi yang Dapat Diakses" copy="SICEPOL membantu Anda memperoleh informasi pajak secara ringkas, jelas, dan terpusat."/><div className="prototype-grid info-grid">{information.map(x=><article className="info-card" key={x.title}><span className="prototype-icon">{x.icon}</span><h3>{x.title}</h3><p>{x.copy}</p></article>)}</div></div></section>
  <section className="prototype-section announcement-section"><div className="container"><SectionHead kicker="Tetap terinformasi" title="Informasi & Pengumuman Terkini" copy="Informasi umum untuk membantu penggunaan layanan dan menjaga keamanan transaksi pajak Anda."/><div className="prototype-grid notices home-reveal"><article className="notice"><h3>Info Jatuh Tempo</h3><p>Periksa rincian tagihan pada SICEPOL dan pastikan pembayaran dilakukan sesuai batas waktu yang tercantum pada dokumen resmi.</p></article><article className="notice"><h3>Panduan Pembayaran Digital</h3><p>Ikuti petunjuk pada kanal pembayaran resmi dan simpan bukti transaksi hingga pembayaran tercatat.</p></article><article className="notice alert"><h3>Waspada Penipuan</h3><p>Hindari membagikan data pribadi atau kode transaksi dan gunakan hanya saluran resmi pemerintah daerah.</p></article></div></div></section>
  <section className="prototype-section prototype-faq"><div className="container faq-layout"><SectionHead kicker="Pertanyaan umum" title="FAQ SICEPOL" copy="Jawaban ringkas untuk pertanyaan yang sering ditemui saat mengakses informasi pajak."/><div className="faq-list"><details><summary>Di mana saya dapat menemukan NOP?</summary><p>NOP terdiri dari 18 digit dan dapat ditemukan pada SPPT PBB. Masukkan angka tersebut ke kolom pencarian sesuai urutannya.</p></details><details><summary>Mengapa data pajak tidak ditemukan?</summary><p>Pastikan seluruh 18 digit NOP telah dimasukkan dengan benar. Jika data tetap tidak ditemukan, mintalah bantuan Bapenda melalui kanal resmi.</p></details><details><summary>Mengapa pembayaran saya belum tercatat?</summary><p>Pembaruan status dapat memerlukan waktu pemrosesan. Simpan bukti pembayaran dan lakukan pengecekan kembali; hubungi Bapenda bila status belum berubah.</p></details></div></div></section>
  <section className="prototype-cta"><div className="container"><div className="cta-box home-reveal"><div><h2>Butuh Bantuan Terkait SICEPOL?</h2><p>Kunjungi kanal resmi atau kantor Badan Pendapatan Daerah Kabupaten Batu Bara untuk memperoleh bantuan dan informasi lebih lanjut.</p></div><a className="cta-link" href="https://bapenda.batubarakab.go.id/hubungi" target="_blank" rel="noopener noreferrer">Kunjungi Website Bapenda</a></div></div></section>
</main><AppFooter/></div>}
function SectionHead({kicker,title,copy}:{kicker:string;title:string;copy:string}){return <div className="prototype-section-head"><span className="section-kicker">{kicker}</span><h2>{title}</h2><p>{copy}</p></div>}
