import { useMemo, useState, type ReactNode } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import type { Column, Notify, Row } from '../types';
import { money } from '../utils/format';
import { AppIcon } from './AppIcon';

export function Badge({ children, tone }: { children: ReactNode; tone?: string }) { return <span className={`in-badge ${tone || String(children).toLowerCase().replaceAll(' ', '-')}`}>{children}</span>; }
export function PageHeader({ title, description, meta, action }: { title: string; description: string; meta?: string; action?: ReactNode }) { return <header className="in-page-header"><div><h1>{title}</h1><p>{description}</p>{meta && <small><i/> {meta}</small>}</div>{action}</header>; }
export function SummaryCards({ items }: { items: { label: string; value: string; note?: string; tone?: string }[] }) { return <div className="in-summary">{items.map(item => <article key={item.label} className={item.tone || ''}><span>{item.label}</span><strong>{item.value}</strong>{item.note && <small>{item.note}</small>}</article>)}</div>; }
export function FilterPanel({ onApply }: { onApply: () => void }) { const [year,setYear]=useState('2026'); const [period,setPeriod]=useState('Januari – September'); const [type,setType]=useState('Semua Pendapatan'); const reset=()=>{setYear('2026');setPeriod('Januari – September');setType('Semua Pendapatan')}; return <section className="in-filter"><div className="in-filter-fields"><label>Tahun Anggaran<select value={year} onChange={e=>setYear(e.target.value)}><option>2026</option><option>2025</option></select></label><label>Periode<select value={period} onChange={e=>setPeriod(e.target.value)}><option>Januari – September</option><option>Triwulan III</option><option>September</option></select></label><label>Jenis Pendapatan<select value={type} onChange={e=>setType(e.target.value)}><option>Semua Pendapatan</option><option>Pajak Daerah</option><option>Retribusi</option></select></label></div><div className="in-filter-actions"><button className="in-btn ghost" onClick={reset}>Reset</button><button className="in-btn primary" onClick={onApply}>Terapkan Filter</button></div></section>; }
const retributionTypes = [
  'Retribusi Pelayanan Kesehatan - Puskesmas',
  'Retribusi Pelayanan Kesehatan - RSUD',
  'Retribusi Pelayanan Kebersihan (Dinas Perumahan, Kawasan Permukiman dan Lingkungan Hidup)',
  'Retribusi Pelayanan Parkir di Tepi Jalan Umum (Dinas Perhubungan)',
  'Retribusi Pelayanan Pasar (Dinas Ketenagakerjaan, Perindustrian dan Perdagangan)',
  'Retribusi PKB - Mobil Bus - Microbus - (Dinas Perhubungan)',
  'Retribusi PKB - Mobil Bus - Bus - (Dinas Perhubungan)',
  'Retribusi PKB - Mobil Barang/Beban - Pick Up (Dinas Perhubungan)',
  'Retribusi PKB - Mobil Barang/Beban - Light Truck (Dinas Perhubungan)',
  'Retribusi PKB - Mobil Barang/Beban - Truck (Dinas Perhubungan)',
  'Retribusi Pemeriksaan Alat Pemadam Kebakaran (Satpol-PP)',
  'Retribusi Pengendalian Menara Telekomunikasi (Dinas PUTR)',
  'Retribusi Pelayanan Tera Ulang (Dinas Ketenagakerjaan, Perindustrian dan Perdagangan)',
  'Retribusi Tempat Pelelangan Ternak - (Dinas Perikanan dan Peternakan)',
  'Retribusi Pelayanan Tempat Rekreasi, Pariwisata dan Olah Raga (Dispora)',
  'Retribusi Persetujuan Bangunan Gedung (PBG) (Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu)',
  'Retribusi Pemberian Izin Trayek - (Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu)',
  'Retribusi Pemberian Izin Usaha Perikanan - (Dinas Perikanan dan Peternakan)',
  'Retribusi Penyediaan Tempat Khusus Parkir di Luar Badan Jalan (Dinas Perhubungan)',
  'Retribusi Pemanfaatan Aset Daerah (Dinas PUTR)',
  'Retribusi Tempat Pelelangan Ikan (TPI) - (Dinas Perikanan dan Peternakan)',
  'Retribusi Pengendalian Lalu Lintas (Dinas Perhubungan)',
  'Retribusi Pelayanan Jasa Kepelabuhan (Dinas Perhubungan)',
  'Retribusi Pelayanan Penyeberangan Orang atau Barang dengan Menggunakan Kendaraan di Air (Dinas Perhubungan)',
  'Retribusi Penyediaan Tempat Kegiatan Usaha (Dinas Ketenagakerjaan, Perindustrian dan Perdagangan)',
  'Retribusi Penyediaan Tempat Pelelangan (Dinas Perikanan dan Peternakan)',
  'Retribusi Pelayanan Rumah Pemotongan Hewan Ternak (Dinas Perikanan dan Peternakan)',
  'Retribusi Penyediaan Tempat Penginapan/Pesanggrahan/Vila (Dispora)',
];

export function RetributionFilterPanel({ onApply }: { onApply: () => void }) { const currentYear=new Date().getFullYear(); const years=Array.from({length:Math.max(1,currentYear-2019)},(_,index)=>String(currentYear-index)); const [type,setType]=useState('Semua Jenis Retribusi'); const [period,setPeriod]=useState('Semua Masa'); const [year,setYear]=useState(String(currentYear)); const reset=()=>{setType('Semua Jenis Retribusi');setPeriod('Semua Masa');setYear(String(currentYear))}; return <section className="in-filter"><div className="in-filter-fields"><label>Jenis Retribusi<select value={type} onChange={e=>setType(e.target.value)}><option>Semua Jenis Retribusi</option>{retributionTypes.map(option=><option key={option} value={option}>{option}</option>)}</select></label><label>Tahun Retribusi<select value={year} onChange={e=>setYear(e.target.value)}>{years.map(option=><option key={option}>{option}</option>)}</select></label><label>Masa Retribusi<select value={period} onChange={e=>setPeriod(e.target.value)}><option>Semua Masa</option><option>Januari</option><option>Februari</option><option>Maret</option><option>April</option><option>Mei</option><option>Juni</option><option>Juli</option><option>Agustus</option><option>September</option><option>Oktober</option><option>November</option><option>Desember</option></select></label></div><div className="in-filter-actions"><button className="in-btn ghost" onClick={reset}>Reset</button><button className="in-btn primary" onClick={onApply}>Terapkan Filter</button></div></section>; }
export function OpdMealsFilterPanel({ onApply }: { onApply: () => void }) { const currentYear=new Date().getFullYear(); const years=Array.from({length:Math.max(1,currentYear-2019)},(_,index)=>String(currentYear-index)); const [month,setMonth]=useState('Semua Bulan'); const [year,setYear]=useState(String(currentYear)); const reset=()=>{setMonth('Semua Bulan');setYear(String(currentYear))}; return <section className="in-filter"><div className="in-filter-fields"><label>Tahun Transaksi<select value={year} onChange={e=>setYear(e.target.value)}>{years.map(option=><option key={option}>{option}</option>)}</select></label><label>Bulan Transaksi<select value={month} onChange={e=>setMonth(e.target.value)}><option>Semua Bulan</option><option>Januari</option><option>Februari</option><option>Maret</option><option>April</option><option>Mei</option><option>Juni</option><option>Juli</option><option>Agustus</option><option>September</option><option>Oktober</option><option>November</option><option>Desember</option></select></label></div><div className="in-filter-actions"><button className="in-btn ghost" onClick={reset}>Reset</button><button className="in-btn primary" onClick={onApply}>Terapkan Filter</button></div></section>; }
export function SimpadaFilterPanel({ onApply }: { onApply: () => void }) { const currentYear=new Date().getFullYear(); const years=Array.from({length:Math.max(1,currentYear-2019)},(_,index)=>String(currentYear-index)); const [year,setYear]=useState(String(currentYear)); const [month,setMonth]=useState('Semua Bulan'); const reset=()=>{setYear(String(currentYear));setMonth('Semua Bulan')}; return <section className="in-filter"><div className="in-filter-fields"><label>Tahun Cetak<select value={year} onChange={e=>setYear(e.target.value)}>{years.map(option=><option key={option}>{option}</option>)}</select></label><label>Bulan Cetak<select value={month} onChange={e=>setMonth(e.target.value)}><option>Semua Bulan</option><option>Januari</option><option>Februari</option><option>Maret</option><option>April</option><option>Mei</option><option>Juni</option><option>Juli</option><option>Agustus</option><option>September</option><option>Oktober</option><option>November</option><option>Desember</option></select></label></div><div className="in-filter-actions"><button className="in-btn ghost" onClick={reset}>Reset</button><button className="in-btn primary" onClick={onApply}>Terapkan Filter</button></div></section>; }
export function DataTable({ columns, rows, search=true, pageSizeOptions=[10, 25, 50, 100] }: { columns: Column[]; rows: Row[]; search?: boolean; pageSizeOptions?: number[] }) { const [query,setQuery]=useState(''); const [sort,setSort]=useState(columns[0].key); const [asc,setAsc]=useState(true); const [page,setPage]=useState(1); const [size,setSize]=useState(pageSizeOptions[0]); const filtered=useMemo(()=>rows.filter(r=>Object.values(r).join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>String(a[sort]).localeCompare(String(b[sort]),'id',{numeric:true})*(asc?1:-1)),[rows,query,sort,asc]); const pages=Math.max(1,Math.ceil(filtered.length/size)),shown=filtered.slice((page-1)*size,page*size); const order=(key:string)=>{if(sort===key)setAsc(!asc);else{setSort(key);setAsc(true)}}; return <section className="in-table-card">{search&&<div className="in-table-tools">{pageSizeOptions?<label className="in-page-size">Tampilkan<select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{pageSizeOptions.map(option=><option key={option} value={option}>{option}</option>)}</select>data</label>:<div><h2>Daftar Data</h2><span>{filtered.length} data ditemukan</span></div>}<label className="in-search">⌕<input aria-label="Cari data" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Cari nomor atau nama..."/></label></div>}<div className="in-table-scroll"><table className={`in-table ${columns.some(c=>c.width)?'has-column-widths':''}`}><colgroup>{columns.map(c=><col key={c.key} style={c.width?{width:c.width}:undefined}/>)}</colgroup><thead><tr>{columns.map(c=><th key={c.key}><button onClick={()=>order(c.key)}>{c.label}{sort===c.key?(asc?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{shown.map((row,i)=><tr key={i}>{columns.map(c=><td key={c.key} className={c.money?'number':''}>{c.key==='status'?<Badge>{row[c.key]}</Badge>:c.key==='action'?<button className="in-table-action">{row[c.key] || 'Detail'}</button>:c.money?money(row[c.key]):row[c.key]}</td>)}</tr>)}</tbody></table>{!shown.length&&<div className="in-empty"><b>⌕</b><strong>Data tidak ditemukan</strong><span>Coba ubah kata kunci atau filter yang digunakan.</span></div>}</div><footer className="in-pagination"><span>Menampilkan {shown.length} dari {filtered.length} data</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>‹</button><b>{page}</b><span>dari {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>›</button></div></footer></section>; }
export function Tabs({ items }: { items: string[] }) { const navigate=useNavigate(); const loc=useLocation(); const selected=new URLSearchParams(loc.search).get('tab')||items[0]; return <div className="in-tabs" role="tablist">{items.map(tab=><button role="tab" aria-selected={selected===tab} className={selected===tab?'active':''} onClick={()=>navigate(`?tab=${encodeURIComponent(tab)}`)} key={tab}>{tab}</button>)}</div>; }
export function ExportButton({ notify }: { notify: Notify }) { return <button className="in-btn excel" onClick={()=>notify('Permintaan ekspor berhasil dibuat dan sedang diproses.')}><AppIcon name="excel"/> Ekspor Excel</button>; }
